### ISSUE TITLE
Feature request: change texture for grout?

### ISSUE THREAD

**Issue by Bluberry-Kat** [maideniles/Maiden-s-Marvelous-Materials#13]
Not that I think it's a bad texture, but it feels confusing.
With Grout, since you use a water bucket to make it, it may initially make the player think that they've duplicated their bucket.
I think changing the grout texture to something else, sans-bucket, would clear up any potential confusion.

**Comment by maideniles** [comment]
thank you for the suggestion; i'll implement that in my next update :)

**Comment by maideniles** [comment]
I've made a new texture for the grout item. I did leave it in a bucket though, because the item is supposed to be a bucket full of the grout. That's why the bucket of water is one of the ingredients--you need something to put it in. :)   But hopefully the way I did the new texture, there won't be any confusion between this and any other bucket. I hope you like the changes. Closing this issue. :)
